name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .  # katalog do deployu, tu cały projekt
      - uses: actions/deploy-pages@v4

      steps:
  - uses: actions/checkout@v4
  - name: Build site
    run: |
      npm install
      npm run build
  - uses: actions/configure-pages@v5
  - uses: actions/upload-pages-artifact@v3
    with:
      path: ./build # lub inny folder z wygenerowanymi plikami
  - uses: actions/deploy-pages@v4